package people.management.entities;

// Generated 2 Jun, 2014 4:48:02 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlAddressLine generated by hbm2java
 */
@Entity
@Table(name = "PL_AddressLine", schema = "dbo", catalog = "PeopleManagement")
public class PlAddressLine implements java.io.Serializable {

	private int addressLineId;
	private PlAddress plAddress;
	private Serializable addressLine;

	public PlAddressLine() {
	}

	public PlAddressLine(int addressLineId) {
		this.addressLineId = addressLineId;
	}

	public PlAddressLine(int addressLineId, PlAddress plAddress,
			Serializable addressLine) {
		this.addressLineId = addressLineId;
		this.plAddress = plAddress;
		this.addressLine = addressLine;
	}

	@Id
	@Column(name = "AddressLineId", unique = true, nullable = false)
	public int getAddressLineId() {
		return this.addressLineId;
	}

	public void setAddressLineId(int addressLineId) {
		this.addressLineId = addressLineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AddressId")
	public PlAddress getPlAddress() {
		return this.plAddress;
	}

	public void setPlAddress(PlAddress plAddress) {
		this.plAddress = plAddress;
	}

	@Column(name = "AddressLine")
	public Serializable getAddressLine() {
		return this.addressLine;
	}

	public void setAddressLine(Serializable addressLine) {
		this.addressLine = addressLine;
	}

}
