package people.management.entities;

// Generated 2 Jun, 2014 4:48:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlEmployeeAgreement generated by hbm2java
 */
@Entity
@Table(name = "PL_Employee_Agreement", schema = "dbo", catalog = "PeopleManagement")
public class PlEmployeeAgreement implements java.io.Serializable {

	private int empId;
	private String empName;
	private String levelId;
	private String allowanceType;
	private String allowanceName;
	private int amt;
	private String taxable;
	private Integer percentage;
	private Date agreementDate;

	public PlEmployeeAgreement() {
	}

	public PlEmployeeAgreement(int empId, String empName, String allowanceType,
			String allowanceName, int amt) {
		this.empId = empId;
		this.empName = empName;
		this.allowanceType = allowanceType;
		this.allowanceName = allowanceName;
		this.amt = amt;
	}

	public PlEmployeeAgreement(int empId, String empName, String levelId,
			String allowanceType, String allowanceName, int amt,
			String taxable, Integer percentage, Date agreementDate) {
		this.empId = empId;
		this.empName = empName;
		this.levelId = levelId;
		this.allowanceType = allowanceType;
		this.allowanceName = allowanceName;
		this.amt = amt;
		this.taxable = taxable;
		this.percentage = percentage;
		this.agreementDate = agreementDate;
	}

	@Id
	@Column(name = "EmpId", unique = true, nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@Column(name = "EmpName", nullable = false, length = 20)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "LevelId", length = 20)
	public String getLevelId() {
		return this.levelId;
	}

	public void setLevelId(String levelId) {
		this.levelId = levelId;
	}

	@Column(name = "AllowanceType", nullable = false, length = 50)
	public String getAllowanceType() {
		return this.allowanceType;
	}

	public void setAllowanceType(String allowanceType) {
		this.allowanceType = allowanceType;
	}

	@Column(name = "AllowanceName", nullable = false, length = 20)
	public String getAllowanceName() {
		return this.allowanceName;
	}

	public void setAllowanceName(String allowanceName) {
		this.allowanceName = allowanceName;
	}

	@Column(name = "Amt", nullable = false)
	public int getAmt() {
		return this.amt;
	}

	public void setAmt(int amt) {
		this.amt = amt;
	}

	@Column(name = "Taxable", length = 5)
	public String getTaxable() {
		return this.taxable;
	}

	public void setTaxable(String taxable) {
		this.taxable = taxable;
	}

	@Column(name = "Percentage")
	public Integer getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Integer percentage) {
		this.percentage = percentage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AgreementDate", length = 10)
	public Date getAgreementDate() {
		return this.agreementDate;
	}

	public void setAgreementDate(Date agreementDate) {
		this.agreementDate = agreementDate;
	}

}
