package people.management.entities;

// Generated 2 Jun, 2014 4:48:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PlUsers generated by hbm2java
 */
@Entity
@Table(name = "PL_Users", schema = "dbo", catalog = "PeopleManagement", uniqueConstraints = @UniqueConstraint(columnNames = "Username"))
public class PlUsers implements java.io.Serializable {

	private int userId;
	private String username;
	private String password;

	public PlUsers() {
	}

	public PlUsers(int userId, String username, String password) {
		this.userId = userId;
		this.username = username;
		this.password = password;
	}

	@Id
	@Column(name = "UserId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "Username", unique = true, nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", nullable = false, length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
