package mypack;

// Generated 29 May, 2014 11:40:42 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product", schema = "dbo", catalog = "PeopleManagement")
public class Product implements java.io.Serializable {

	private int id;
	private String name;
	private Integer price;
	private Integer qty;

	public Product() {
	}

	public Product(int id) {
		this.id = id;
	}

	public Product(int id, String name, Integer price, Integer qty) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.qty = qty;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

}
