package mypack;

// Generated 3 Jan, 2010 1:01:32 AM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerPersonId generated by hbm2java
 */
@Embeddable
public class CustomerPersonId implements java.io.Serializable {

	private int customerCustomerId;
	private int personBookTransId;

	public CustomerPersonId() {
	}

	public CustomerPersonId(int customerCustomerId, int personBookTransId) {
		this.customerCustomerId = customerCustomerId;
		this.personBookTransId = personBookTransId;
	}

	@Column(name = "customer_Customer_ID", nullable = false)
	public int getCustomerCustomerId() {
		return this.customerCustomerId;
	}

	public void setCustomerCustomerId(int customerCustomerId) {
		this.customerCustomerId = customerCustomerId;
	}

	@Column(name = "person_Book_Trans_ID", unique = true, nullable = false)
	public int getPersonBookTransId() {
		return this.personBookTransId;
	}

	public void setPersonBookTransId(int personBookTransId) {
		this.personBookTransId = personBookTransId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomerPersonId))
			return false;
		CustomerPersonId castOther = (CustomerPersonId) other;

		return (this.getCustomerCustomerId() == castOther
				.getCustomerCustomerId())
				&& (this.getPersonBookTransId() == castOther
						.getPersonBookTransId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomerCustomerId();
		result = 37 * result + this.getPersonBookTransId();
		return result;
	}

}
