package mypack;

// Generated 24 Jan, 2014 1:04:04 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Package generated by hbm2java
 */
@Entity
@Table(name = "package", catalog = "etour")
public class Package implements java.io.Serializable {

	private Integer packageId;
	private String categoryId;
	private String subCategoryId;
	private String categoryDesc;
	private String imgPath;
	private Boolean flag;

	public Package() {
	}

	public Package(String categoryId, String subCategoryId,
			String categoryDesc, String imgPath, Boolean flag) {
		this.categoryId = categoryId;
		this.subCategoryId = subCategoryId;
		this.categoryDesc = categoryDesc;
		this.imgPath = imgPath;
		this.flag = flag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Package_ID", unique = true, nullable = false)
	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	@Column(name = "Category_ID", length = 10)
	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "SubCategory_ID", length = 10)
	public String getSubCategoryId() {
		return this.subCategoryId;
	}

	public void setSubCategoryId(String subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	@Column(name = "Category_Desc", length = 20)
	public String getCategoryDesc() {
		return this.categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	@Column(name = "Img_Path", length = 40)
	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	@Column(name = "Flag")
	public Boolean getFlag() {
		return this.flag;
	}

	public void setFlag(Boolean flag) {
		this.flag = flag;
	}

}
