package mypack;

// Generated 23 Jan, 2014 3:05:40 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tourinfo generated by hbm2java
 */
@Entity
@Table(name = "tourinfo", catalog = "etour")
public class Tourinfo implements java.io.Serializable {

	private String subCategoryId;
	private String productDesc;
	private Integer duration;
	private Integer cost;
	private String imgPath;

	public Tourinfo() {
	}

	public Tourinfo(String subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	public Tourinfo(String subCategoryId, String productDesc, Integer duration,
			Integer cost, String imgPath) {
		this.subCategoryId = subCategoryId;
		this.productDesc = productDesc;
		this.duration = duration;
		this.cost = cost;
		this.imgPath = imgPath;
	}

	@Id
	@Column(name = "SubCategory_ID", unique = true, nullable = false, length = 10)
	public String getSubCategoryId() {
		return this.subCategoryId;
	}

	public void setSubCategoryId(String subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	@Column(name = "Product_Desc", length = 20)
	public String getProductDesc() {
		return this.productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	@Column(name = "Duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "Cost")
	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	@Column(name = "Img_Path", length = 50)
	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	@Override
	public String toString() {
		return "Tourinfo [subCategoryId=" + subCategoryId + ", productDesc="
				+ productDesc + ", duration=" + duration + ", cost=" + cost
				+ ", imgPath=" + imgPath + "]";
	}

}
